languages:
  - id: py3
    name: Python 3
    source_filename: solution.py
    run:
      cmd: /usr/bin/python3
      args: ["{{source}}"]
      limits:
        wall_time_s: 9
        memory_kb: 102400
        max_processes: 100

  - id: cpp
    name: C++
    source_filename: solution.cpp
    artifact: solution
    build:
      cmd: /usr/bin/g++
      args: ["-o", "{{artifact}}", "{{source}}"]
      limits:
        wall_time_s: 3
        memory_kb: 1048576
        max_processes: 100
      flag_allowlist: ["-O0","-O1","-O2","-O3","-Wall","-Wextra","-std=c++17"]
    run:
      cmd: "{{artifact}}"
      limits:
        wall_time_s: 3
        memory_kb: 524288
        max_processes: 64

  - id: java
    name: Java
    source_filename_strategy: from_request
    build:
      cmd: /usr/bin/javac
      args: ["{{source}}"]
      limits:
        wall_time_s: 6
        memory_kb: 512000
        max_processes: 100
    run:
      cmd: /usr/bin/java
      args: ["{{artifact}}"]
      limits:
        wall_time_s: 6
        memory_kb: 512000
        max_processes: 100

  - id: bash
    name: Bash
    source_filename: solution.sh
    run:
      cmd: /bin/bash
      args: ["{{source}}"]
      limits:
        wall_time_s: 9
        memory_kb: 102400
        max_processes: 100

  - id: js
    name: JavaScript
    source_filename: solution.js
    run:
      cmd: /usr/bin/node
      args: ["{{source}}"]
      limits:
        wall_time_s: 9
        memory_kb: 204800
        max_processes: 100

  - id: c
    name: C
    source_filename: solution.c
    artifact: solution
    build:
      cmd: /usr/bin/gcc
      args: ["-o", "{{artifact}}", "{{source}}"]
      limits:
        wall_time_s: 3
        memory_kb: 1048576
        max_processes: 100
      flag_allowlist: ["-O0","-O1","-O2","-O3","-Wall","-std=c11"]
    run:
      cmd: "{{artifact}}"
      limits:
        wall_time_s: 3
        memory_kb: 524288
        max_processes: 64

  - id: verilog
    name: Verilog
    source_filename: solution.v
    artifact: solution
    build:
      cmd: /usr/bin/iverilog
      args: ["-o", "{{artifact}}", "{{source}}"]
      limits:
        wall_time_s: 5
        memory_kb: 1048576
        max_processes: 100
    run:
      cmd: /usr/bin/vvp
      args: ["{{artifact}}"]
      limits:
        wall_time_s: 5
        memory_kb: 204800
        max_processes: 64
        